//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftProtobuf open source project
//
// Copyright (c) 2019 Circuit Dragon, Ltd.
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//
//
// VarintFrameDecoderTests+XCTest.swift
//
import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.rb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension VarintFrameDecoderTests {

   static var allTests : [(String, (VarintFrameDecoderTests) -> () throws -> Void)] {
      return [
                ("testDecodingIndividualBytes", testDecodingIndividualBytes),
                ("testDecodingEntireFrame", testDecodingEntireFrame),
                ("testEmptyBuffer", testEmptyBuffer),
           ]
   }
}

